import type { L } from "./i18n"

/**
 * UI strings for the site chrome: footer, mobile dock, header menu,
 * command palette, install prompt, theme picker, offline/PWA notices.
 * Kept in its own module so localization sweeps don't collide in
 * i18n.ts; merged into the UI dictionary there.
 */
export const UI_CHROME = {
  // ── Footer ─────────────────────────────────────────────────────
  ftStudio: { en: "Studio", nl: "Studio", zh: "工作室", hi: "स्टूडियो", es: "Estudio", fr: "Studio", ar: "الاستوديو", pt: "Estúdio", ru: "Студия", de: "Studio", ja: "スタジオ" },
  ftKnowledgeGraph: { en: "Knowledge Graph", nl: "Kennisgraaf", zh: "知识图谱", hi: "ज्ञान ग्राफ़", es: "Grafo del conocimiento", fr: "Graphe du savoir", ar: "الرسم البياني للمعرفة", pt: "Grafo do conhecimento", ru: "Граф знаний", de: "Wissensgraph", ja: "知識グラフ" },
  ftLearningPaths: { en: "Learning Paths", nl: "Leerpaden", zh: "学习路径", hi: "सीखने के मार्ग", es: "Rutas de aprendizaje", fr: "Parcours d’apprentissage", ar: "مسارات التعلّم", pt: "Trilhas de aprendizado", ru: "Учебные маршруты", de: "Lernpfade", ja: "学習パス" },
  ftHowItWorks: { en: "How it works", nl: "Hoe het werkt", zh: "运作方式", hi: "यह कैसे काम करता है", es: "Cómo funciona", fr: "Comment ça marche", ar: "كيف يعمل", pt: "Como funciona", ru: "Как это работает", de: "So funktioniert es", ja: "仕組み" },
  ftViewGithub: { en: "View on GitHub", nl: "Bekijk op GitHub", zh: "在 GitHub 上查看", hi: "GitHub पर देखें", es: "Ver en GitHub", fr: "Voir sur GitHub", ar: "عرض على GitHub", pt: "Ver no GitHub", ru: "Смотреть на GitHub", de: "Auf GitHub ansehen", ja: "GitHub で見る" },
  ftGoodFirstIssues: { en: "Good first issues", nl: "Goede eerste issues", zh: "适合新手的议题", hi: "शुरुआत के लिए अच्छे मुद्दे", es: "Buenas primeras tareas", fr: "Bonnes premières contributions", ar: "مهام أولى مناسبة", pt: "Boas primeiras tarefas", ru: "Задачи для новичков", de: "Gute Einstiegsaufgaben", ja: "初心者向けイシュー" },
  ftPeerReview: { en: "Peer review", nl: "Peerreview", zh: "同行评审", hi: "सहकर्मी समीक्षा", es: "Revisión por pares", fr: "Évaluation par les pairs", ar: "مراجعة الأقران", pt: "Revisão por pares", ru: "Рецензирование", de: "Peer-Review", ja: "ピアレビュー" },
  ftOurMission: { en: "Our mission", nl: "Onze missie", zh: "我们的使命", hi: "हमारा मिशन", es: "Nuestra misión", fr: "Notre mission", ar: "مهمتنا", pt: "Nossa missão", ru: "Наша миссия", de: "Unsere Mission", ja: "私たちの使命" },
  ftAboutEquilibrium: { en: "About Equilibrium", nl: "Over Equilibrium", zh: "关于 Equilibrium", hi: "Equilibrium के बारे में", es: "Acerca de Equilibrium", fr: "À propos d’Equilibrium", ar: "حول Equilibrium", pt: "Sobre o Equilibrium", ru: "Об Equilibrium", de: "Über Equilibrium", ja: "Equilibrium について" },
  ftOpenLicence: { en: "Open licence", nl: "Open licentie", zh: "开放许可", hi: "खुला लाइसेंस", es: "Licencia abierta", fr: "Licence ouverte", ar: "رخصة مفتوحة", pt: "Licença aberta", ru: "Открытая лицензия", de: "Offene Lizenz", ja: "オープンライセンス" },
  ftTagline: { en: "The world’s living knowledge ecosystem for regenerative thinking. Free, open and endlessly connected.", nl: "Het levende kennisecosysteem van de wereld voor regeneratief denken. Vrij, open en eindeloos verbonden.", zh: "面向再生思维的全球活知识生态系统。免费、开放、无尽相连。", hi: "पुनर्योजी सोच के लिए दुनिया का जीवंत ज्ञान पारितंत्र। मुफ़्त, खुला और अनंत रूप से जुड़ा हुआ।", es: "El ecosistema vivo de conocimiento del mundo para el pensamiento regenerativo. Libre, abierto e infinitamente conectado.", fr: "L’écosystème vivant du savoir mondial pour la pensée régénérative. Libre, ouvert et infiniment relié.", ar: "منظومة المعرفة الحيّة في العالم للفكر التجديدي. مجانية ومفتوحة ومترابطة بلا حدود.", pt: "O ecossistema vivo de conhecimento do mundo para o pensamento regenerativo. Livre, aberto e infinitamente conectado.", ru: "Живая мировая экосистема знаний для регенеративного мышления. Свободная, открытая и бесконечно связанная.", de: "Das lebendige Wissensökosystem der Welt für regeneratives Denken. Frei, offen und endlos vernetzt.", ja: "リジェネラティブな思考のための、世界の生きた知識エコシステム。無料で、開かれ、限りなくつながる。" },
  ftCopyright: { en: "Equilibrium — a side brand of GRØNN Studio. Content under CC BY-SA 4.0.", nl: "Equilibrium — een zijmerk van GRØNN Studio. Inhoud onder CC BY-SA 4.0.", zh: "Equilibrium — GRØNN Studio 的副品牌。内容采用 CC BY-SA 4.0 许可。", hi: "Equilibrium — GRØNN Studio का एक सह-ब्रांड। सामग्री CC BY-SA 4.0 के अंतर्गत।", es: "Equilibrium — una marca de GRØNN Studio. Contenido bajo CC BY-SA 4.0.", fr: "Equilibrium — une marque de GRØNN Studio. Contenu sous CC BY-SA 4.0.", ar: "Equilibrium — علامة فرعية من GRØNN Studio. المحتوى مرخّص بموجب CC BY-SA 4.0.", pt: "Equilibrium — uma marca da GRØNN Studio. Conteúdo sob CC BY-SA 4.0.", ru: "Equilibrium — суббренд GRØNN Studio. Материалы под лицензией CC BY-SA 4.0.", de: "Equilibrium — eine Nebenmarke von GRØNN Studio. Inhalte unter CC BY-SA 4.0.", ja: "Equilibrium — GRØNN Studio のサイドブランド。コンテンツは CC BY-SA 4.0 の下で提供。" },
  ftBuiltWith: { en: "Built with", nl: "Gebouwd met", zh: "满怀", hi: "बनाया गया", es: "Hecho con", fr: "Construit avec", ar: "صُنع بـ", pt: "Feito com", ru: "Создано с", de: "Gebaut mit", ja: "生物圏への" },
  ftForBiosphere: { en: "for the biosphere", nl: "voor de biosfeer", zh: "为生物圈打造", hi: "जैवमंडल के लिए, प्रेम से", es: "para la biosfera", fr: "pour la biosphère", ar: "من أجل الغلاف الحيوي", pt: "para a biosfera", ru: "для биосферы", de: "für die Biosphäre", ja: "を込めて" },
  ftSource: { en: "Source", nl: "Broncode", zh: "源代码", hi: "स्रोत", es: "Código fuente", fr: "Code source", ar: "المصدر", pt: "Código-fonte", ru: "Исходный код", de: "Quellcode", ja: "ソース" },
  // ── Mobile dock ────────────────────────────────────────────────
  dockSoil: { en: "Soil", nl: "Bodem", zh: "土壤", hi: "मिट्टी", es: "Suelo", fr: "Sol", ar: "التربة", pt: "Solo", ru: "Почва", de: "Boden", ja: "土壌" },
  dockWater: { en: "Water", nl: "Water", zh: "水", hi: "जल", es: "Agua", fr: "Eau", ar: "الماء", pt: "Água", ru: "Вода", de: "Wasser", ja: "水" },
  dockFungi: { en: "Fungi", nl: "Schimmels", zh: "真菌", hi: "कवक", es: "Hongos", fr: "Champignons", ar: "الفطريات", pt: "Fungos", ru: "Грибы", de: "Pilze", ja: "菌類" },
  dockPermaculture: { en: "Permaculture", nl: "Permacultuur", zh: "朴门永续", hi: "पर्माकल्चर", es: "Permacultura", fr: "Permaculture", ar: "الزراعة المستدامة", pt: "Permacultura", ru: "Пермакультура", de: "Permakultur", ja: "パーマカルチャー" },
  dockSheetLabel: { en: "Site navigation", nl: "Sitenavigatie", zh: "网站导航", hi: "साइट नेविगेशन", es: "Navegación del sitio", fr: "Navigation du site", ar: "التنقّل في الموقع", pt: "Navegação do site", ru: "Навигация по сайту", de: "Website-Navigation", ja: "サイトナビゲーション" },
  dockLabel: { en: "Mobile dock", nl: "Mobiel dock", zh: "移动端导航栏", hi: "मोबाइल डॉक", es: "Barra móvil", fr: "Dock mobile", ar: "شريط الجوال", pt: "Dock móvel", ru: "Мобильная панель", de: "Mobiles Dock", ja: "モバイルドック" },
  dockBackToTop: { en: "Back to top", nl: "Terug naar boven", zh: "回到顶部", hi: "ऊपर जाएँ", es: "Volver arriba", fr: "Retour en haut", ar: "العودة إلى الأعلى", pt: "Voltar ao topo", ru: "Наверх", de: "Nach oben", ja: "トップへ戻る" },
  // ── Header ─────────────────────────────────────────────────────
  menuHomeAria: { en: "Equilibrium — Home", nl: "Equilibrium — Home", zh: "Equilibrium — 首页", hi: "Equilibrium — होम", es: "Equilibrium — Inicio", fr: "Equilibrium — Accueil", ar: "Equilibrium — الرئيسية", pt: "Equilibrium — Início", ru: "Equilibrium — Главная", de: "Equilibrium — Startseite", ja: "Equilibrium — ホーム" },
  menuSiteMenu: { en: "Site menu", nl: "Sitemenu", zh: "网站菜单", hi: "साइट मेन्यू", es: "Menú del sitio", fr: "Menu du site", ar: "قائمة الموقع", pt: "Menu do site", ru: "Меню сайта", de: "Seitenmenü", ja: "サイトメニュー" },
  // ── Mega menu ──────────────────────────────────────────────────
  megaDiscover: { en: "Discover", nl: "Ontdek", zh: "发现", hi: "खोजें", es: "Descubre", fr: "Découvrir", ar: "اكتشف", pt: "Descubra", ru: "Открывайте", de: "Entdecken", ja: "発見" },
  megaEvidence: { en: "Evidence", nl: "Onderbouwing", zh: "证据", hi: "प्रमाण", es: "Evidencia", fr: "Preuves", ar: "الأدلة", pt: "Evidência", ru: "Доказательства", de: "Belege", ja: "エビデンス" },
  megaPartners: { en: "Partners", nl: "Partners", zh: "合作伙伴", hi: "साझेदार", es: "Socios", fr: "Partenaires", ar: "الشركاء", pt: "Parceiros", ru: "Партнёры", de: "Partner", ja: "パートナー" },
  megaSeasonal: { en: "Seasonal guide", nl: "Seizoensgids", zh: "时令指南", hi: "मौसमी मार्गदर्शिका", es: "Guía estacional", fr: "Guide saisonnier", ar: "دليل الفصول", pt: "Guia sazonal", ru: "Сезонный гид", de: "Saisonführer", ja: "季節ガイド" },
  megaWizard: { en: "Contribution wizard", nl: "Bijdrage-wizard", zh: "贡献向导", hi: "योगदान विज़ार्ड", es: "Asistente de contribución", fr: "Assistant de contribution", ar: "معالج المساهمة", pt: "Assistente de contribuição", ru: "Мастер вклада", de: "Beitrags-Assistent", ja: "貢献ウィザード" },
  megaSources: { en: "Source registry", nl: "Bronnenregister", zh: "来源登记", hi: "स्रोत सूची", es: "Registro de fuentes", fr: "Registre des sources", ar: "سجل المصادر", pt: "Registro de fontes", ru: "Реестр источников", de: "Quellenregister", ja: "ソース登録" },
  megaRss: { en: "RSS feed", nl: "RSS-feed", zh: "RSS 订阅", hi: "RSS फ़ीड", es: "Canal RSS", fr: "Flux RSS", ar: "خلاصة RSS", pt: "Feed RSS", ru: "RSS-лента", de: "RSS-Feed", ja: "RSS フィード" },
  // ── Theme picker ───────────────────────────────────────────────
  themeGoldenHour: { en: "Golden Hour", nl: "Gouden uur", zh: "金色时刻", hi: "गोल्डन आवर", es: "Hora dorada", fr: "Heure dorée", ar: "الساعة الذهبية", pt: "Hora dourada", ru: "Золотой час", de: "Goldene Stunde", ja: "ゴールデンアワー" },
  themeBlueHour: { en: "Blue Hour", nl: "Blauwe uur", zh: "蓝色时刻", hi: "ब्लू आवर", es: "Hora azul", fr: "Heure bleue", ar: "الساعة الزرقاء", pt: "Hora azul", ru: "Синий час", de: "Blaue Stunde", ja: "ブルーアワー" },
  themeSwitchDay: { en: "Switch to Golden Hour", nl: "Wissel naar Gouden uur", zh: "切换到金色时刻", hi: "गोल्डन आवर पर जाएँ", es: "Cambiar a Hora dorada", fr: "Passer à l’Heure dorée", ar: "التبديل إلى الساعة الذهبية", pt: "Mudar para Hora dourada", ru: "Переключить на Золотой час", de: "Zur Goldenen Stunde wechseln", ja: "ゴールデンアワーに切り替える" },
  themeSwitchNight: { en: "Switch to Blue Hour", nl: "Wissel naar Blauwe uur", zh: "切换到蓝色时刻", hi: "ब्लू आवर पर जाएँ", es: "Cambiar a Hora azul", fr: "Passer à l’Heure bleue", ar: "التبديل إلى الساعة الزرقاء", pt: "Mudar para Hora azul", ru: "Переключить на Синий час", de: "Zur Blauen Stunde wechseln", ja: "ブルーアワーに切り替える" },
  // ── Command palette ────────────────────────────────────────────
  palClose: { en: "Close search", nl: "Zoeken sluiten", zh: "关闭搜索", hi: "खोज बंद करें", es: "Cerrar búsqueda", fr: "Fermer la recherche", ar: "إغلاق البحث", pt: "Fechar busca", ru: "Закрыть поиск", de: "Suche schließen", ja: "検索を閉じる" },
  palDialogLabel: { en: "Search Equilibrium", nl: "Doorzoek Equilibrium", zh: "搜索 Equilibrium", hi: "Equilibrium में खोजें", es: "Buscar en Equilibrium", fr: "Rechercher dans Equilibrium", ar: "ابحث في Equilibrium", pt: "Buscar no Equilibrium", ru: "Поиск по Equilibrium", de: "Equilibrium durchsuchen", ja: "Equilibrium を検索" },
  palPlaceholder: { en: "Search the ecosystem — try “fungi” or “water”", nl: "Doorzoek het ecosysteem — probeer ‘schimmels’ of ‘water’", zh: "搜索生态系统 — 试试“真菌”或“水”", hi: "पारितंत्र में खोजें — “कवक” या “जल” आज़माएँ", es: "Busca en el ecosistema — prueba «hongos» o «agua»", fr: "Recherchez dans l’écosystème — essayez « champignons » ou « eau »", ar: "ابحث في المنظومة — جرّب «الفطريات» أو «الماء»", pt: "Busque no ecossistema — tente “fungos” ou “água”", ru: "Ищите по экосистеме — попробуйте «грибы» или «вода»", de: "Das Ökosystem durchsuchen — z. B. „Pilze“ oder „Wasser“", ja: "生態系を検索 — 「菌類」や「水」を試してみて" },
  palTrending: { en: "Trending", nl: "Populair", zh: "热门", hi: "लोकप्रिय", es: "Tendencias", fr: "Tendances", ar: "الرائج", pt: "Em alta", ru: "Популярное", de: "Beliebt", ja: "トレンド" },
  palEmpty: { en: "No matches yet — the ecosystem is always growing.", nl: "Nog geen resultaten — het ecosysteem groeit altijd door.", zh: "暂无匹配结果 — 生态系统仍在不断生长。", hi: "अभी कोई परिणाम नहीं — पारितंत्र निरंतर बढ़ रहा है।", es: "Aún no hay coincidencias — el ecosistema siempre está creciendo.", fr: "Pas encore de résultat — l’écosystème ne cesse de grandir.", ar: "لا نتائج بعد — المنظومة في نموّ دائم.", pt: "Nenhum resultado ainda — o ecossistema está sempre crescendo.", ru: "Пока ничего не найдено — экосистема постоянно растёт.", de: "Noch keine Treffer — das Ökosystem wächst ständig weiter.", ja: "まだ一致なし — 生態系は成長し続けています。" },
  // ── Install prompt / PWA ───────────────────────────────────────
  pwaInstallAria: { en: "Install Equilibrium", nl: "Installeer Equilibrium", zh: "安装 Equilibrium", hi: "Equilibrium इंस्टॉल करें", es: "Instalar Equilibrium", fr: "Installer Equilibrium", ar: "تثبيت Equilibrium", pt: "Instalar o Equilibrium", ru: "Установить Equilibrium", de: "Equilibrium installieren", ja: "Equilibrium をインストール" },
  pwaTitle: { en: "Keep Equilibrium on your home screen", nl: "Zet Equilibrium op je beginscherm", zh: "把 Equilibrium 放到主屏幕", hi: "Equilibrium को अपनी होम स्क्रीन पर रखें", es: "Lleva Equilibrium a tu pantalla de inicio", fr: "Gardez Equilibrium sur votre écran d’accueil", ar: "احتفظ بـ Equilibrium على شاشتك الرئيسية", pt: "Mantenha o Equilibrium na sua tela inicial", ru: "Добавьте Equilibrium на главный экран", de: "Equilibrium auf dem Startbildschirm behalten", ja: "Equilibrium をホーム画面に追加" },
  pwaTapThe: { en: "Tap the", nl: "Tik op de", zh: "点按下方的", hi: "नीचे", es: "Toca el botón de", fr: "Touchez le bouton", ar: "اضغط على زر", pt: "Toque no botão de", ru: "Нажмите кнопку", de: "Tippe unten auf", ja: "下の" },
  pwaShare: { en: "share", nl: "deelknop", zh: "分享按钮", hi: "शेयर बटन", es: "compartir", fr: "partager", ar: "المشاركة", pt: "compartilhar", ru: "«Поделиться»", de: "Teilen", ja: "共有ボタン" },
  pwaIosMid: { en: "button below, then", nl: "hieronder en kies dan", zh: "，然后选择", hi: "पर टैप करें, फिर", es: "abajo y luego", fr: "ci-dessous, puis", ar: "أدناه، ثم اختر", pt: "abaixo e depois", ru: "внизу, затем выберите", de: "und wähle dann", ja: "をタップし、" },
  pwaA2HS: { en: "“Add to Home Screen”", nl: "‘Zet op beginscherm’", zh: "“添加到主屏幕”", hi: "“होम स्क्रीन पर जोड़ें”", es: "«Añadir a pantalla de inicio»", fr: "« Sur l’écran d’accueil »", ar: "«إضافة إلى الشاشة الرئيسية»", pt: "“Adicionar à Tela de Início”", ru: "«На экран “Домой”»", de: "„Zum Home-Bildschirm“", ja: "「ホーム画面に追加」" },
  pwaOpensLikeApp: { en: "— it opens like an app.", nl: "— het opent als een app.", zh: "— 它会像应用一样打开。", hi: "— यह ऐप की तरह खुलता है।", es: "— se abre como una app.", fr: "— il s’ouvre comme une appli.", ar: "— يُفتح كأنه تطبيق.", pt: "— abre como um app.", ru: "— откроется как приложение.", de: "— es öffnet sich wie eine App.", ja: "を選ぶと、アプリのように開きます。" },
  pwaOpenMenu: { en: "Open the browser", nl: "Open het", zh: "打开浏览器", hi: "ब्राउज़र का", es: "Abre el", fr: "Ouvrez le", ar: "افتح", pt: "Abra o", ru: "Откройте", de: "Öffne das", ja: "ブラウザの" },
  pwaMenuGlyph: { en: "menu (⋮)", nl: "browsermenu (⋮)", zh: "菜单 (⋮)", hi: "मेन्यू (⋮)", es: "menú del navegador (⋮)", fr: "menu du navigateur (⋮)", ar: "قائمة المتصفح (⋮)", pt: "menu do navegador (⋮)", ru: "меню браузера (⋮)", de: "Browser-Menü (⋮)", ja: "メニュー (⋮)" },
  pwaMenuMid: { en: "and choose", nl: "en kies", zh: "，选择", hi: "खोलें, फिर चुनें", es: "y elige", fr: "puis choisissez", ar: "ثم اختر", pt: "e escolha", ru: "и выберите", de: "und wähle", ja: "を開き、" },
  pwaAndroidBody: { en: "Installs in a second — opens fullscreen, straight to the living graph.", nl: "Geïnstalleerd in een tel — opent op volledig scherm, recht naar de levende graaf.", zh: "秒装即用 — 全屏打开，直达生生不息的图谱。", hi: "पलक झपकते इंस्टॉल — फ़ुलस्क्रीन में खुलता है, सीधे जीवंत ग्राफ़ तक।", es: "Se instala en un segundo — se abre a pantalla completa, directo al grafo vivo.", fr: "Installée en une seconde — s’ouvre en plein écran, droit vers le graphe vivant.", ar: "يُثبَّت في ثانية — يُفتح بملء الشاشة مباشرةً إلى الرسم البياني الحي.", pt: "Instala em um segundo — abre em tela cheia, direto no grafo vivo.", ru: "Установка за секунду — открывается на весь экран, прямо к живому графу.", de: "In einer Sekunde installiert — öffnet im Vollbild, direkt zum lebendigen Graphen.", ja: "一瞬でインストール — フルスクリーンで開き、生きたグラフへ直行。" },
  pwaInstall: { en: "Install", nl: "Installeren", zh: "安装", hi: "इंस्टॉल करें", es: "Instalar", fr: "Installer", ar: "تثبيت", pt: "Instalar", ru: "Установить", de: "Installieren", ja: "インストール" },
  pwaDismiss: { en: "Dismiss", nl: "Sluiten", zh: "关闭", hi: "हटाएँ", es: "Descartar", fr: "Ignorer", ar: "إغلاق", pt: "Dispensar", ru: "Скрыть", de: "Schließen", ja: "閉じる" },
  // ── Pull to refresh ────────────────────────────────────────────
  pwaRefreshing: { en: "Refreshing", nl: "Vernieuwen", zh: "正在刷新", hi: "रीफ़्रेश हो रहा है", es: "Actualizando", fr: "Actualisation", ar: "جارٍ التحديث", pt: "Atualizando", ru: "Обновление", de: "Aktualisieren", ja: "更新中" },
  pwaReleaseRefresh: { en: "Release to refresh", nl: "Loslaten om te vernieuwen", zh: "松开即可刷新", hi: "रीफ़्रेश के लिए छोड़ें", es: "Suelta para actualizar", fr: "Relâchez pour actualiser", ar: "أفلت للتحديث", pt: "Solte para atualizar", ru: "Отпустите для обновления", de: "Loslassen zum Aktualisieren", ja: "離して更新" },
  pwaPullRefresh: { en: "Pull to refresh", nl: "Trek om te vernieuwen", zh: "下拉刷新", hi: "रीफ़्रेश के लिए खींचें", es: "Desliza para actualizar", fr: "Tirez pour actualiser", ar: "اسحب للتحديث", pt: "Puxe para atualizar", ru: "Потяните для обновления", de: "Ziehen zum Aktualisieren", ja: "引っ張って更新" },
} satisfies Record<string, L>
