import type { L } from "./i18n"

/**
 * UI strings for the inner pages: /knowledge, /learn, /explore,
 * /community, article pages, not-found, offline. Kept in its own
 * module so localization sweeps don't collide in i18n.ts; merged into
 * the UI dictionary there.
 */
export const UI_PAGES = {
  // Difficulty levels (badges)
  diffFoundational: { en: "Foundational", nl: "Fundamenteel", zh: "基础", hi: "आधारभूत", es: "Fundamental", fr: "Fondamental", ar: "تأسيسي", pt: "Fundamental", ru: "Базовый", de: "Grundlegend", ja: "基礎" },
  diffIntermediate: { en: "Intermediate", nl: "Gevorderd", zh: "进阶", hi: "मध्यम", es: "Intermedio", fr: "Intermédiaire", ar: "متوسط", pt: "Intermediário", ru: "Средний", de: "Mittelstufe", ja: "中級" },
  diffAdvanced: { en: "Advanced", nl: "Expert", zh: "高级", hi: "उन्नत", es: "Avanzado", fr: "Avancé", ar: "متقدم", pt: "Avançado", ru: "Продвинутый", de: "Fortgeschritten", ja: "上級" },

  // Knowledge index
  knLibrary: { en: "The library", nl: "De bibliotheek", zh: "知识库", hi: "पुस्तकालय", es: "La biblioteca", fr: "La bibliothèque", ar: "المكتبة", pt: "A biblioteca", ru: "Библиотека", de: "Die Bibliothek", ja: "ライブラリー" },
  knHeadline: { en: "Twenty-four domains, one connected whole.", nl: "Vierentwintig domeinen, één verbonden geheel.", zh: "二十四个领域，一个相连的整体。", hi: "चौबीस क्षेत्र, एक जुड़ा हुआ समग्र।", es: "Veinticuatro dominios, un todo conectado.", fr: "Vingt-quatre domaines, un tout relié.", ar: "أربعة وعشرون مجالاً، كلٌّ واحد مترابط.", pt: "Vinte e quatro domínios, um todo conectado.", ru: "Двадцать четыре области — одно связанное целое.", de: "Vierundzwanzig Bereiche, ein verbundenes Ganzes.", ja: "24の分野、ひとつにつながる全体。" },
  knBody: { en: "Each domain is a doorway. Follow the one that calls to you — every path eventually meets the others.", nl: "Elk domein is een deuropening. Volg het domein dat je roept — elk pad komt uiteindelijk de andere tegen.", zh: "每个领域都是一扇门。跟随召唤你的那一扇——所有路径终将相遇。", hi: "हर क्षेत्र एक द्वार है। जो आपको बुलाए उसका अनुसरण करें — हर पथ अंततः दूसरों से मिलता है।", es: "Cada dominio es una puerta. Sigue el que te llame: todos los caminos acaban encontrándose.", fr: "Chaque domaine est une porte. Suivez celui qui vous appelle — chaque chemin finit par rejoindre les autres.", ar: "كل مجال باب. اتبع ما يناديك — فكل طريق يلتقي في النهاية بالطرق الأخرى.", pt: "Cada domínio é uma porta. Siga o que chama você — todo caminho acaba encontrando os outros.", ru: "Каждая область — это дверь. Идите за той, что зовёт вас: все пути в итоге встречаются.", de: "Jeder Bereich ist eine Tür. Folge dem, der dich ruft — jeder Pfad trifft irgendwann die anderen.", ja: "それぞれの分野は扉です。呼びかけてくる扉を進んでください——どの道もやがて他の道と交わります。" },

  // Category page
  knReading: { en: "Reading", nl: "Leestijd", zh: "阅读", hi: "पठन", es: "Lectura", fr: "Lecture", ar: "القراءة", pt: "Leitura", ru: "Чтение", de: "Lesezeit", ja: "読了" },
  knMin: { en: "min", nl: "min", zh: "分钟", hi: "मिनट", es: "min", fr: "min", ar: "دقيقة", pt: "min", ru: "мин", de: "Min.", ja: "分" },
  knEmptyLead: { en: "This domain is still taking root. Seed articles are on the way —", nl: "Dit domein schiet nog wortel. De eerste artikelen zijn onderweg —", zh: "这个领域仍在扎根。种子文章即将到来——", hi: "यह क्षेत्र अभी जड़ पकड़ रहा है। शुरुआती लेख रास्ते में हैं —", es: "Este dominio aún está echando raíces. Los primeros artículos están en camino:", fr: "Ce domaine prend encore racine. Les premiers articles arrivent —", ar: "لا يزال هذا المجال يتجذر. المقالات الأولى في الطريق —", pt: "Este domínio ainda está criando raízes. Os primeiros artigos estão a caminho —", ru: "Эта область ещё пускает корни. Первые статьи уже в пути —", de: "Dieser Bereich schlägt noch Wurzeln. Die ersten Artikel sind unterwegs —", ja: "この分野はまだ根を張り始めたばかり。最初の記事は準備中です——" },
  knEmptyLink: { en: "contribute the first one", nl: "draag het eerste bij", zh: "贡献第一篇", hi: "पहला लेख योगदान करें", es: "contribuye el primero", fr: "contribuez le premier", ar: "ساهم بالمقال الأول", pt: "contribua com o primeiro", ru: "внесите первую", de: "steuere den ersten bei", ja: "最初の一本を寄稿する" },
  knRelatedDomains: { en: "Related domains", nl: "Verwante domeinen", zh: "相关领域", hi: "संबंधित क्षेत्र", es: "Dominios relacionados", fr: "Domaines liés", ar: "مجالات ذات صلة", pt: "Domínios relacionados", ru: "Связанные области", de: "Verwandte Bereiche", ja: "関連する分野" },
  knArticleWord: { en: "article", nl: "artikel", zh: "篇文章", hi: "लेख", es: "artículo", fr: "article", ar: "مقال", pt: "artigo", ru: "статья", de: "Artikel", ja: "記事" },
  knArticlesWord: { en: "articles", nl: "artikelen", zh: "篇文章", hi: "लेख", es: "artículos", fr: "articles", ar: "مقالات", pt: "artigos", ru: "статей", de: "Artikel", ja: "記事" },
  knLinksWord: { en: "links", nl: "links", zh: "个链接", hi: "कड़ियाँ", es: "enlaces", fr: "liens", ar: "روابط", pt: "links", ru: "связей", de: "Verknüpfungen", ja: "リンク" },
  knFieldStory: { en: "Field Story", nl: "Veldverhaal", zh: "田野故事", hi: "क्षेत्र कथा", es: "Historia de campo", fr: "Récit de terrain", ar: "قصة ميدانية", pt: "História de campo", ru: "Полевая история", de: "Feldgeschichte", ja: "フィールドストーリー" },

  // Article page
  artMinRead: { en: "min read", nl: "min leestijd", zh: "分钟阅读", hi: "मिनट का पठन", es: "min de lectura", fr: "min de lecture", ar: "دقيقة قراءة", pt: "min de leitura", ru: "мин чтения", de: "Min. Lesezeit", ja: "分で読める" },
  artConnectionsWord: { en: "connections", nl: "verbindingen", zh: "个连接", hi: "संबंध", es: "conexiones", fr: "connexions", ar: "روابط", pt: "conexões", ru: "связей", de: "Verbindungen", ja: "つながり" },
  artContributorsWord: { en: "contributors", nl: "bijdragers", zh: "位贡献者", hi: "योगदानकर्ता", es: "colaboradores", fr: "contributeurs", ar: "مساهمون", pt: "colaboradores", ru: "участников", de: "Mitwirkende", ja: "人の貢献者" },
  artUpdated: { en: "Updated", nl: "Bijgewerkt", zh: "更新于", hi: "अद्यतन", es: "Actualizado", fr: "Mis à jour", ar: "حُدّث", pt: "Atualizado", ru: "Обновлено", de: "Aktualisiert", ja: "更新" },
  artReferences: { en: "References", nl: "Bronnen", zh: "参考文献", hi: "संदर्भ", es: "Referencias", fr: "Références", ar: "المراجع", pt: "Referências", ru: "Источники", de: "Quellen", ja: "参考文献" },
  artSourceLink: { en: "link", nl: "link", zh: "链接", hi: "कड़ी", es: "enlace", fr: "lien", ar: "رابط", pt: "link", ru: "ссылка", de: "Link", ja: "リンク" },
  artImprove: { en: "Improve this page", nl: "Verbeter deze pagina", zh: "改进此页", hi: "इस पृष्ठ को सुधारें", es: "Mejora esta página", fr: "Améliorer cette page", ar: "حسّن هذه الصفحة", pt: "Melhore esta página", ru: "Улучшить страницу", de: "Diese Seite verbessern", ja: "このページを改善する" },
  artImproveBody: { en: "Every article is open source and freely licensed. Spot an error, add a citation or sharpen a sentence — edits flow through peer review to publication.", nl: "Elk artikel is open source en vrij gelicentieerd. Zie je een fout, voeg een bron toe of scherp een zin aan — bewerkingen gaan via peer review naar publicatie.", zh: "每篇文章都是开源且自由授权的。发现错误、补充引用或润色句子——修改经同行评审后发布。", hi: "हर लेख ओपन सोर्स और मुक्त लाइसेंस वाला है। कोई त्रुटि देखें, संदर्भ जोड़ें या वाक्य निखारें — संपादन समीक्षा से होकर प्रकाशित होते हैं।", es: "Cada artículo es de código abierto y con licencia libre. Detecta un error, añade una cita o pule una frase: los cambios pasan por revisión de pares hasta publicarse.", fr: "Chaque article est open source et sous licence libre. Repérez une erreur, ajoutez une citation ou affûtez une phrase — les modifications passent par la relecture avant publication.", ar: "كل مقال مفتوح المصدر ومرخّص بحرية. اكتشف خطأً أو أضف مرجعاً أو حسّن جملة — تمر التعديلات بالمراجعة قبل النشر.", pt: "Cada artigo é open source e com licença livre. Encontre um erro, adicione uma citação ou aprimore uma frase — as edições passam por revisão até a publicação.", ru: "Каждая статья — открытый код со свободной лицензией. Заметили ошибку, добавьте источник или отточите фразу — правки проходят рецензирование и публикуются.", de: "Jeder Artikel ist Open Source und frei lizenziert. Finde einen Fehler, ergänze eine Quelle oder schärfe einen Satz — Änderungen gehen per Peer-Review in die Veröffentlichung.", ja: "すべての記事はオープンソースで自由なライセンスの下にあります。誤りを見つけたら、引用を加えたり文章を磨いたり——編集は査読を経て公開されます。" },
  artEditGitHub: { en: "Edit on GitHub", nl: "Bewerk op GitHub", zh: "在 GitHub 上编辑", hi: "GitHub पर संपादित करें", es: "Editar en GitHub", fr: "Modifier sur GitHub", ar: "حرر على GitHub", pt: "Editar no GitHub", ru: "Редактировать на GitHub", de: "Auf GitHub bearbeiten", ja: "GitHub で編集" },
  artHowContrib: { en: "How contributing works", nl: "Hoe bijdragen werkt", zh: "如何参与贡献", hi: "योगदान कैसे काम करता है", es: "Cómo funciona la contribución", fr: "Comment contribuer", ar: "كيف تعمل المساهمة", pt: "Como funciona a contribuição", ru: "Как устроен вклад", de: "So funktioniert das Mitwirken", ja: "貢献のしくみ" },
  artOnThisPage: { en: "On this page", nl: "Op deze pagina", zh: "本页内容", hi: "इस पृष्ठ पर", es: "En esta página", fr: "Sur cette page", ar: "في هذه الصفحة", pt: "Nesta página", ru: "На этой странице", de: "Auf dieser Seite", ja: "このページの内容" },
  artContributors: { en: "Contributors", nl: "Bijdragers", zh: "贡献者", hi: "योगदानकर्ता", es: "Colaboradores", fr: "Contributeurs", ar: "المساهمون", pt: "Colaboradores", ru: "Участники", de: "Mitwirkende", ja: "貢献者" },
  artOpenSource: { en: "Open source", nl: "Open source", zh: "开源", hi: "ओपन सोर्स", es: "Código abierto", fr: "Open source", ar: "مفتوح المصدر", pt: "Código aberto", ru: "Открытый код", de: "Open Source", ja: "オープンソース" },
  artViewSource: { en: "View source", nl: "Bekijk bron", zh: "查看源码", hi: "स्रोत देखें", es: "Ver fuente", fr: "Voir la source", ar: "عرض المصدر", pt: "Ver fonte", ru: "Исходник", de: "Quelltext ansehen", ja: "ソースを見る" },
  artHistory: { en: "Version history", nl: "Versiegeschiedenis", zh: "版本历史", hi: "संस्करण इतिहास", es: "Historial de versiones", fr: "Historique des versions", ar: "سجل الإصدارات", pt: "Histórico de versões", ru: "История версий", de: "Versionsverlauf", ja: "変更履歴" },
  artDiscussion: { en: "Discussion", nl: "Discussie", zh: "讨论", hi: "चर्चा", es: "Discusión", fr: "Discussion", ar: "النقاش", pt: "Discussão", ru: "Обсуждение", de: "Diskussion", ja: "ディスカッション" },
  artFollowThreads: { en: "Follow the threads", nl: "Volg de draden", zh: "顺藤摸瓜", hi: "धागों का अनुसरण करें", es: "Sigue los hilos", fr: "Suivez les fils", ar: "اتبع الخيوط", pt: "Siga os fios", ru: "Идите по нитям", de: "Den Fäden folgen", ja: "糸をたどる" },

  // Learn page
  learnHeadline: { en: "Learn the way ecosystems teach — by connection.", nl: "Leer zoals ecosystemen onderwijzen — via verbinding.", zh: "以生态系统的方式学习——通过连接。", hi: "जैसे पारितंत्र सिखाते हैं, वैसे सीखें — जुड़ाव से।", es: "Aprende como enseñan los ecosistemas: por conexión.", fr: "Apprenez comme enseignent les écosystèmes — par la connexion.", ar: "تعلّم كما تعلّم النظم البيئية — بالترابط.", pt: "Aprenda como os ecossistemas ensinam — por conexão.", ru: "Учитесь так, как учат экосистемы — через связи.", de: "Lerne, wie Ökosysteme lehren — durch Verbindung.", ja: "生態系が教えるように学ぶ——つながりを通して。" },
  learnBody: { en: "Each path is a curated sequence of articles that build on one another. Track progress, take notes, and watch the graph light up as you go.", nl: "Elk pad is een samengestelde reeks artikelen die op elkaar voortbouwen. Volg je voortgang, maak notities en zie de graaf oplichten terwijl je vordert.", zh: "每条路径都是一组精心编排、层层递进的文章。跟踪进度、做笔记，看着图谱随你前行而点亮。", hi: "हर पथ लेखों का चुना हुआ क्रम है जो एक-दूसरे पर आधारित हैं। प्रगति देखें, नोट्स लें और आगे बढ़ते हुए ग्राफ़ को जगमगाते देखें।", es: "Cada ruta es una secuencia curada de artículos que se apoyan entre sí. Sigue tu progreso, toma notas y mira cómo se ilumina el grafo a tu paso.", fr: "Chaque parcours est une séquence d'articles qui se construisent les uns sur les autres. Suivez vos progrès, prenez des notes et regardez le graphe s'illuminer au fil du chemin.", ar: "كل مسار سلسلة منتقاة من المقالات يبني بعضها على بعض. تتبّع تقدمك ودوّن ملاحظاتك وشاهد الرسم البياني يضيء وأنت تمضي.", pt: "Cada trilha é uma sequência curada de artigos que se apoiam uns nos outros. Acompanhe o progresso, faça anotações e veja o grafo se iluminar pelo caminho.", ru: "Каждый путь — подобранная последовательность статей, опирающихся друг на друга. Следите за прогрессом, делайте заметки и смотрите, как граф загорается по мере продвижения.", de: "Jeder Pfad ist eine kuratierte Abfolge von Artikeln, die aufeinander aufbauen. Verfolge deinen Fortschritt, mach Notizen und sieh zu, wie der Graph unterwegs aufleuchtet.", ja: "各パスは、互いに積み重なる記事の厳選されたシーケンスです。進捗を記録し、メモを取り、進むにつれてグラフが灯るのを見てください。" },
  learnSoon: { en: "Soon", nl: "Binnenkort", zh: "即将推出", hi: "जल्द ही", es: "Pronto", fr: "Bientôt", ar: "قريباً", pt: "Em breve", ru: "Скоро", de: "Bald", ja: "近日公開" },

  // Explore page
  expLabel: { en: "Knowledge graph", nl: "Kennisgraaf", zh: "知识图谱", hi: "ज्ञान ग्राफ़", es: "Grafo de conocimiento", fr: "Graphe de savoir", ar: "رسم المعرفة البياني", pt: "Grafo de conhecimento", ru: "Граф знаний", de: "Wissensgraph", ja: "ナレッジグラフ" },
  expHeadline: { en: "The whole ecosystem, in one view.", nl: "Het hele ecosysteem, in één oogopslag.", zh: "整个生态系统，尽收眼底。", hi: "पूरा पारितंत्र, एक दृश्य में।", es: "Todo el ecosistema, en una sola vista.", fr: "Tout l'écosystème, en un seul regard.", ar: "المنظومة كلها في مشهد واحد.", pt: "Todo o ecossistema, em uma só vista.", ru: "Вся экосистема — одним взглядом.", de: "Das ganze Ökosystem auf einen Blick.", ja: "生態系のすべてを、ひと目で。" },
  expBody: { en: "{articles} concepts woven by {connections} relationships across {categories} domains. Filter by domain, then follow the threads.", nl: "{articles} concepten, verweven door {connections} relaties over {categories} domeinen. Filter op domein en volg dan de draden.", zh: "{articles} 个概念由 {connections} 段关系编织，横跨 {categories} 个领域。按领域筛选，然后顺着丝线探索。", hi: "{categories} क्षेत्रों में {connections} संबंधों से बुने {articles} अवधारणाएँ। क्षेत्र से छानें, फिर धागों का अनुसरण करें।", es: "{articles} conceptos tejidos por {connections} relaciones en {categories} dominios. Filtra por dominio y sigue los hilos.", fr: "{articles} concepts tissés par {connections} relations à travers {categories} domaines. Filtrez par domaine, puis suivez les fils.", ar: "{articles} مفهوماً تنسجها {connections} علاقة عبر {categories} مجالاً. رشّح حسب المجال ثم اتبع الخيوط.", pt: "{articles} conceitos tecidos por {connections} relações em {categories} domínios. Filtre por domínio e siga os fios.", ru: "{articles} понятий, сплетённых {connections} связями в {categories} областях. Отфильтруйте по области и идите по нитям.", de: "{articles} Konzepte, verwoben durch {connections} Beziehungen über {categories} Bereiche. Nach Bereich filtern, dann den Fäden folgen.", ja: "{categories} の分野にわたり、{connections} の関係で織られた {articles} の概念。分野で絞り込み、糸をたどってください。" },

  // Community page
  comLabel: { en: "Built in public", nl: "Openbaar gebouwd", zh: "公开构建", hi: "सार्वजनिक रूप से निर्मित", es: "Construido en público", fr: "Construit en public", ar: "يُبنى علناً", pt: "Construído em público", ru: "Создаётся публично", de: "Öffentlich gebaut", ja: "公開の場で作られる" },
  comHeadline: { en: "Knowledge as a commons, tended by many hands.", nl: "Kennis als gemeengoed, verzorgd door vele handen.", zh: "知识作为公共资源，由众人之手照料。", hi: "साझा संपदा के रूप में ज्ञान, अनेक हाथों से सँवारा।", es: "El conocimiento como bien común, cuidado por muchas manos.", fr: "Le savoir comme bien commun, entretenu par de nombreuses mains.", ar: "المعرفة مشاعٌ ترعاه أيادٍ كثيرة.", pt: "O conhecimento como bem comum, cuidado por muitas mãos.", ru: "Знание как общее достояние, взращиваемое многими руками.", de: "Wissen als Gemeingut, gepflegt von vielen Händen.", ja: "多くの手で育てられる、コモンズとしての知識。" },
  comBody: { en: "Equilibrium belongs to everyone. It grows through the same open, version-controlled workflow that builds the world's best software — applied to the world's ecological knowledge.", nl: "Equilibrium is van iedereen. Het groeit via dezelfde open, versiebeheerde workflow waarmee de beste software ter wereld wordt gebouwd — toegepast op de ecologische kennis van de wereld.", zh: "Equilibrium 属于每一个人。它通过与世界顶级软件相同的开放式版本控制流程成长——只是应用于世界的生态知识。", hi: "Equilibrium सबका है। यह उसी खुले, संस्करण-नियंत्रित वर्कफ़्लो से बढ़ता है जिससे दुनिया का सर्वश्रेष्ठ सॉफ़्टवेयर बनता है — बस विश्व के पारिस्थितिक ज्ञान पर लागू।", es: "Equilibrium pertenece a todos. Crece con el mismo flujo abierto y versionado que construye el mejor software del mundo, aplicado al conocimiento ecológico del planeta.", fr: "Equilibrium appartient à tous. Il grandit grâce au même flux ouvert et versionné qui construit les meilleurs logiciels du monde — appliqué au savoir écologique mondial.", ar: "Equilibrium ملك للجميع. ينمو عبر سير العمل المفتوح نفسه القائم على التحكم بالإصدارات الذي يبني أفضل برمجيات العالم — مطبقاً على معرفة العالم البيئية.", pt: "O Equilibrium pertence a todos. Ele cresce pelo mesmo fluxo aberto e versionado que constrói o melhor software do mundo — aplicado ao conhecimento ecológico do planeta.", ru: "Equilibrium принадлежит всем. Он растёт через тот же открытый процесс с контролем версий, что создаёт лучшее ПО мира, — применённый к экологическим знаниям планеты.", de: "Equilibrium gehört allen. Es wächst über denselben offenen, versionierten Workflow, mit dem die beste Software der Welt entsteht — angewandt auf das ökologische Wissen der Welt.", ja: "Equilibrium はみんなのものです。世界最高のソフトウェアを生み出すのと同じ、オープンでバージョン管理されたワークフローで成長します——それを世界の生態学的知識に適用して。" },
  comStartGitHub: { en: "Start on GitHub", nl: "Begin op GitHub", zh: "从 GitHub 开始", hi: "GitHub पर शुरू करें", es: "Empieza en GitHub", fr: "Commencer sur GitHub", ar: "ابدأ على GitHub", pt: "Comece no GitHub", ru: "Начать на GitHub", de: "Auf GitHub starten", ja: "GitHub で始める" },
  comReadLicence: { en: "Read the licence", nl: "Lees de licentie", zh: "阅读许可协议", hi: "लाइसेंस पढ़ें", es: "Leer la licencia", fr: "Lire la licence", ar: "اقرأ الرخصة", pt: "Ler a licença", ru: "Прочитать лицензию", de: "Lizenz lesen", ja: "ライセンスを読む" },
  comFlow: { en: "The contribution flow", nl: "De bijdrage-stroom", zh: "贡献流程", hi: "योगदान प्रवाह", es: "El flujo de contribución", fr: "Le flux de contribution", ar: "مسار المساهمة", pt: "O fluxo de contribuição", ru: "Путь вклада", de: "Der Beitragsfluss", ja: "貢献の流れ" },
  comStep1t: { en: "Fork & edit", nl: "Fork & bewerk", zh: "复刻与编辑", hi: "फ़ोर्क और संपादन", es: "Bifurca y edita", fr: "Forker et modifier", ar: "انسخ وحرر", pt: "Faça fork e edite", ru: "Форк и правка", de: "Forken & bearbeiten", ja: "フォークして編集" },
  comStep1b: { en: "Every article has an “Improve this page” link that opens the source in GitHub. Fix a typo, add a citation or write a whole new page in Markdown.", nl: "Elk artikel heeft een link “Verbeter deze pagina” die de bron in GitHub opent. Herstel een typfout, voeg een bron toe of schrijf een hele nieuwe pagina in Markdown.", zh: "每篇文章都有“改进此页”链接，可在 GitHub 中打开源文件。修正笔误、补充引用，或用 Markdown 写一整篇新页面。", hi: "हर लेख में “इस पृष्ठ को सुधारें” कड़ी है जो GitHub में स्रोत खोलती है। टाइपो ठीक करें, संदर्भ जोड़ें या Markdown में पूरा नया पृष्ठ लिखें।", es: "Cada artículo tiene un enlace «Mejora esta página» que abre la fuente en GitHub. Corrige una errata, añade una cita o escribe una página nueva en Markdown.", fr: "Chaque article a un lien « Améliorer cette page » qui ouvre la source dans GitHub. Corrigez une coquille, ajoutez une citation ou écrivez une toute nouvelle page en Markdown.", ar: "لكل مقال رابط «حسّن هذه الصفحة» يفتح المصدر في GitHub. صحّح خطأً مطبعياً أو أضف مرجعاً أو اكتب صفحة جديدة كاملة بصيغة Markdown.", pt: "Cada artigo tem um link “Melhore esta página” que abre a fonte no GitHub. Corrija um erro, adicione uma citação ou escreva uma página nova em Markdown.", ru: "У каждой статьи есть ссылка «Улучшить страницу», открывающая исходник на GitHub. Исправьте опечатку, добавьте источник или напишите новую страницу в Markdown.", de: "Jeder Artikel hat einen Link „Diese Seite verbessern“, der die Quelle in GitHub öffnet. Behebe einen Tippfehler, ergänze eine Quelle oder schreibe eine ganz neue Seite in Markdown.", ja: "各記事には GitHub でソースを開く「このページを改善する」リンクがあります。誤字を直したり、引用を加えたり、Markdown で新しいページを丸ごと書いたり。" },
  comStep2t: { en: "Open a pull request", nl: "Open een pull request", zh: "发起拉取请求", hi: "पुल रिक्वेस्ट खोलें", es: "Abre un pull request", fr: "Ouvrir une pull request", ar: "افتح طلب سحب", pt: "Abra um pull request", ru: "Откройте pull request", de: "Pull Request öffnen", ja: "プルリクエストを開く" },
  comStep2b: { en: "Your change becomes a pull request. Automated checks validate frontmatter, citations and links before a human ever looks.", nl: "Je wijziging wordt een pull request. Geautomatiseerde checks valideren frontmatter, bronnen en links voordat een mens ernaar kijkt.", zh: "你的更改会成为一个拉取请求。自动检查会先验证元数据、引用和链接，然后才由人来审阅。", hi: "आपका बदलाव पुल रिक्वेस्ट बन जाता है। किसी इंसान के देखने से पहले स्वचालित जाँचें फ्रंटमैटर, संदर्भ और कड़ियाँ सत्यापित करती हैं।", es: "Tu cambio se convierte en un pull request. Comprobaciones automáticas validan el frontmatter, las citas y los enlaces antes de que lo vea una persona.", fr: "Votre modification devient une pull request. Des vérifications automatiques valident le frontmatter, les citations et les liens avant qu'un humain n'y jette un œil.", ar: "يصبح تغييرك طلب سحب. تتحقق الفحوص الآلية من البيانات الوصفية والمراجع والروابط قبل أن يراها إنسان.", pt: "Sua alteração vira um pull request. Verificações automáticas validam frontmatter, citações e links antes de qualquer olhar humano.", ru: "Ваше изменение становится pull request. Автоматические проверки валидируют метаданные, источники и ссылки ещё до взгляда человека.", de: "Deine Änderung wird ein Pull Request. Automatische Checks prüfen Frontmatter, Quellen und Links, bevor ein Mensch draufschaut.", ja: "変更はプルリクエストになります。人が見る前に、自動チェックがフロントマター・引用・リンクを検証します。" },
  comStep3t: { en: "Peer review", nl: "Peer review", zh: "同行评审", hi: "सहकर्मी समीक्षा", es: "Revisión de pares", fr: "Relecture par les pairs", ar: "مراجعة الأقران", pt: "Revisão por pares", ru: "Рецензирование", de: "Peer-Review", ja: "ピアレビュー" },
  comStep3b: { en: "Contributors review each other's work in the open. Discussion happens on the PR, where anyone can weigh in.", nl: "Bijdragers reviewen elkaars werk in de openbaarheid. Discussie vindt plaats op de PR, waar iedereen kan meepraten.", zh: "贡献者公开互相评审。讨论在 PR 上进行，任何人都可以参与。", hi: "योगदानकर्ता खुले में एक-दूसरे के काम की समीक्षा करते हैं। चर्चा PR पर होती है, जहाँ कोई भी राय दे सकता है।", es: "Los colaboradores revisan el trabajo de los demás en abierto. La discusión ocurre en el PR, donde cualquiera puede opinar.", fr: "Les contributeurs relisent mutuellement leur travail au grand jour. La discussion se déroule sur la PR, où chacun peut intervenir.", ar: "يراجع المساهمون أعمال بعضهم علناً. يجري النقاش على طلب السحب حيث يمكن لأي شخص المشاركة.", pt: "Os colaboradores revisam o trabalho uns dos outros abertamente. A discussão acontece no PR, onde qualquer um pode opinar.", ru: "Участники открыто рецензируют работы друг друга. Обсуждение идёт в PR, где высказаться может каждый.", de: "Mitwirkende prüfen die Arbeit der anderen öffentlich. Diskutiert wird im PR, wo sich jede:r einbringen kann.", ja: "貢献者は互いの作業を公開の場でレビューします。議論は PR 上で行われ、誰でも参加できます。" },
  comStep4t: { en: "Expert verification", nl: "Expertverificatie", zh: "专家验证", hi: "विशेषज्ञ सत्यापन", es: "Verificación experta", fr: "Vérification par des experts", ar: "تحقق الخبراء", pt: "Verificação por especialistas", ru: "Экспертная проверка", de: "Expertenprüfung", ja: "専門家による検証" },
  comStep4b: { en: "Domain experts verify facts and sign off. Verified articles carry a mark of trust and enter the graph.", nl: "Domeinexperts verifiëren feiten en keuren goed. Geverifieerde artikelen dragen een keurmerk en komen in de graaf.", zh: "领域专家核实事实并签署确认。经验证的文章带有信任标记，并进入图谱。", hi: "क्षेत्र विशेषज्ञ तथ्यों की पुष्टि कर स्वीकृति देते हैं। सत्यापित लेख विश्वास चिह्न के साथ ग्राफ़ में आते हैं।", es: "Los expertos del dominio verifican los hechos y dan el visto bueno. Los artículos verificados llevan una marca de confianza y entran en el grafo.", fr: "Les experts du domaine vérifient les faits et valident. Les articles vérifiés portent une marque de confiance et entrent dans le graphe.", ar: "يتحقق خبراء المجال من الحقائق ويوقّعون. تحمل المقالات الموثقة علامة ثقة وتدخل الرسم البياني.", pt: "Especialistas do domínio verificam os fatos e aprovam. Artigos verificados carregam uma marca de confiança e entram no grafo.", ru: "Эксперты области проверяют факты и утверждают. Проверенные статьи получают знак доверия и входят в граф.", de: "Fachleute verifizieren Fakten und geben frei. Verifizierte Artikel tragen ein Vertrauenssiegel und gelangen in den Graphen.", ja: "各分野の専門家が事実を検証し、承認します。検証済みの記事は信頼の印を得てグラフに加わります。" },
  comWhereStart: { en: "Where to start", nl: "Waar te beginnen", zh: "从哪里开始", hi: "कहाँ से शुरू करें", es: "Por dónde empezar", fr: "Par où commencer", ar: "من أين تبدأ", pt: "Por onde começar", ru: "С чего начать", de: "Wo anfangen", ja: "はじめの一歩" },
  comStart1t: { en: "Fix or improve a page", nl: "Herstel of verbeter een pagina", zh: "修正或改进页面", hi: "पृष्ठ ठीक करें या सुधारें", es: "Corrige o mejora una página", fr: "Corriger ou améliorer une page", ar: "أصلح صفحة أو حسّنها", pt: "Corrija ou melhore uma página", ru: "Исправьте или улучшите страницу", de: "Eine Seite korrigieren oder verbessern", ja: "ページを直す・良くする" },
  comStart1b: { en: "Sharpen a sentence, add a missing citation or correct a fact. Edit the source directly on GitHub.", nl: "Scherp een zin aan, voeg een ontbrekende bron toe of corrigeer een feit. Bewerk de bron rechtstreeks op GitHub.", zh: "润色句子、补充缺失的引用或纠正事实。直接在 GitHub 上编辑源文件。", hi: "वाक्य निखारें, छूटा संदर्भ जोड़ें या तथ्य सुधारें। GitHub पर सीधे स्रोत संपादित करें।", es: "Pule una frase, añade una cita que falte o corrige un dato. Edita la fuente directamente en GitHub.", fr: "Affûtez une phrase, ajoutez une citation manquante ou corrigez un fait. Modifiez la source directement sur GitHub.", ar: "حسّن جملة أو أضف مرجعاً ناقصاً أو صحح معلومة. حرر المصدر مباشرة على GitHub.", pt: "Aprimore uma frase, adicione uma citação faltante ou corrija um fato. Edite a fonte diretamente no GitHub.", ru: "Отточите фразу, добавьте недостающий источник или исправьте факт. Редактируйте исходник прямо на GitHub.", de: "Schärfe einen Satz, ergänze eine fehlende Quelle oder korrigiere einen Fakt. Bearbeite die Quelle direkt auf GitHub.", ja: "文章を磨き、足りない引用を加え、事実を正す。GitHub で直接ソースを編集できます。" },
  comStart2t: { en: "Pick a good first issue", nl: "Kies een goede eerste issue", zh: "挑选新手友好议题", hi: "अच्छा पहला इश्यू चुनें", es: "Elige un buen primer issue", fr: "Choisir une bonne première issue", ar: "اختر مهمة أولى مناسبة", pt: "Escolha um bom primeiro issue", ru: "Выберите первую задачу", de: "Ein gutes erstes Issue wählen", ja: "はじめてのイシューを選ぶ" },
  comStart2b: { en: "Small, well-scoped tasks curated for newcomers. A gentle way into the codebase and the content.", nl: "Kleine, goed afgebakende taken samengesteld voor nieuwkomers. Een zachte ingang tot de code en de inhoud.", zh: "为新人精选的小而清晰的任务。温和地进入代码库与内容的方式。", hi: "नवागंतुकों के लिए चुने गए छोटे, सुपरिभाषित कार्य। कोडबेस और सामग्री में प्रवेश का सहज मार्ग।", es: "Tareas pequeñas y bien acotadas para recién llegados. Una entrada amable al código y al contenido.", fr: "Des tâches petites et bien cadrées pour les nouveaux venus. Une entrée en douceur dans le code et le contenu.", ar: "مهام صغيرة محددة بعناية للوافدين الجدد. مدخل لطيف إلى الشيفرة والمحتوى.", pt: "Tarefas pequenas e bem delimitadas para iniciantes. Uma entrada suave no código e no conteúdo.", ru: "Небольшие, чётко очерченные задачи для новичков. Мягкий вход в кодовую базу и контент.", de: "Kleine, klar umrissene Aufgaben für Neulinge. Ein sanfter Einstieg in Code und Inhalt.", ja: "新参者のために厳選された、小さく範囲の明確なタスク。コードとコンテンツへのやさしい入り口です。" },
  comStart3t: { en: "Join the discussion", nl: "Doe mee aan de discussie", zh: "加入讨论", hi: "चर्चा में शामिल हों", es: "Únete a la discusión", fr: "Rejoindre la discussion", ar: "انضم إلى النقاش", pt: "Participe da discussão", ru: "Присоединяйтесь к обсуждению", de: "An der Diskussion teilnehmen", ja: "ディスカッションに参加" },
  comStart3b: { en: "Ask a question, propose a new article or debate an idea. Every contribution starts as a conversation.", nl: "Stel een vraag, stel een nieuw artikel voor of bediscussieer een idee. Elke bijdrage begint als een gesprek.", zh: "提问、提议新文章或探讨想法。每一次贡献都始于一场对话。", hi: "प्रश्न पूछें, नया लेख प्रस्तावित करें या विचार पर बहस करें। हर योगदान बातचीत से शुरू होता है।", es: "Haz una pregunta, propón un artículo nuevo o debate una idea. Toda contribución empieza como una conversación.", fr: "Posez une question, proposez un nouvel article ou débattez d'une idée. Toute contribution commence par une conversation.", ar: "اطرح سؤالاً أو اقترح مقالاً جديداً أو ناقش فكرة. كل مساهمة تبدأ كمحادثة.", pt: "Faça uma pergunta, proponha um artigo novo ou debata uma ideia. Toda contribuição começa como conversa.", ru: "Задайте вопрос, предложите новую статью или обсудите идею. Каждый вклад начинается с разговора.", de: "Stelle eine Frage, schlage einen neuen Artikel vor oder diskutiere eine Idee. Jeder Beitrag beginnt als Gespräch.", ja: "質問し、新しい記事を提案し、アイデアを議論する。すべての貢献は会話から始まります。" },
  comStart4t: { en: "Read the contributor guide", nl: "Lees de bijdragersgids", zh: "阅读贡献者指南", hi: "योगदानकर्ता गाइड पढ़ें", es: "Lee la guía del colaborador", fr: "Lire le guide du contributeur", ar: "اقرأ دليل المساهمين", pt: "Leia o guia do colaborador", ru: "Прочитайте руководство участника", de: "Den Leitfaden für Mitwirkende lesen", ja: "コントリビューターガイドを読む" },
  comStart4b: { en: "How articles are structured, the quality bar and the workflow from fork to verified merge.", nl: "Hoe artikelen zijn opgebouwd, de kwaliteitslat en de workflow van fork tot geverifieerde merge.", zh: "文章如何组织、质量标准，以及从复刻到验证合并的流程。", hi: "लेखों की संरचना, गुणवत्ता मानक और फ़ोर्क से सत्यापित मर्ज तक का वर्कफ़्लो।", es: "Cómo se estructuran los artículos, el listón de calidad y el flujo desde el fork hasta el merge verificado.", fr: "Comment les articles sont structurés, le niveau d'exigence et le flux du fork au merge vérifié.", ar: "كيف تُبنى المقالات، ومعيار الجودة، وسير العمل من النسخ إلى الدمج الموثق.", pt: "Como os artigos são estruturados, o padrão de qualidade e o fluxo do fork ao merge verificado.", ru: "Как устроены статьи, планка качества и процесс от форка до проверенного слияния.", de: "Wie Artikel aufgebaut sind, die Qualitätslatte und der Workflow vom Fork bis zum verifizierten Merge.", ja: "記事の構成、品質基準、フォークから検証済みマージまでのワークフロー。" },
  comGood: { en: "What makes a good article", nl: "Wat een goed artikel maakt", zh: "好文章的标准", hi: "अच्छा लेख क्या बनाता है", es: "Qué hace bueno a un artículo", fr: "Ce qui fait un bon article", ar: "ما الذي يصنع مقالاً جيداً", pt: "O que faz um bom artigo", ru: "Что делает статью хорошей", de: "Was einen guten Artikel ausmacht", ja: "よい記事の条件" },
  comGoodIntro: { en: "Every page is a small act of teaching. Before you open a pull request, hold your draft against this measure.", nl: "Elke pagina is een kleine daad van onderwijzen. Leg je concept langs deze meetlat voordat je een pull request opent.", zh: "每一页都是一次小小的教学。发起拉取请求之前，请以此标准衡量你的草稿。", hi: "हर पृष्ठ सिखाने का एक छोटा कर्म है। पुल रिक्वेस्ट खोलने से पहले अपने मसौदे को इस कसौटी पर परखें।", es: "Cada página es un pequeño acto de enseñanza. Antes de abrir un pull request, mide tu borrador con esta vara.", fr: "Chaque page est un petit acte d'enseignement. Avant d'ouvrir une pull request, mesurez votre brouillon à cette aune.", ar: "كل صفحة فعل تعليم صغير. قبل فتح طلب السحب، قِس مسودتك على هذا المعيار.", pt: "Cada página é um pequeno ato de ensino. Antes de abrir um pull request, avalie seu rascunho por esta medida.", ru: "Каждая страница — маленький акт обучения. Прежде чем открыть pull request, сверьте черновик с этой меркой.", de: "Jede Seite ist ein kleiner Akt des Lehrens. Bevor du einen Pull Request öffnest, miss deinen Entwurf an diesem Maßstab.", ja: "すべてのページは小さな教えの営みです。プルリクエストを開く前に、この基準に照らして草稿を確かめてください。" },
  comCheck1: { en: "One clear idea, explained from the ground up", nl: "Eén helder idee, uitgelegd vanaf de basis", zh: "一个清晰的想法，从头讲透", hi: "एक स्पष्ट विचार, बुनियाद से समझाया", es: "Una idea clara, explicada desde la base", fr: "Une idée claire, expliquée depuis la base", ar: "فكرة واحدة واضحة تُشرح من الأساس", pt: "Uma ideia clara, explicada desde a base", ru: "Одна ясная идея, объяснённая с азов", de: "Eine klare Idee, von Grund auf erklärt", ja: "ひとつの明確なアイデアを、基礎から説明する" },
  comCheck2: { en: "Plain, accessible language over jargon", nl: "Heldere, toegankelijke taal boven jargon", zh: "用平实易懂的语言，而非行话", hi: "शब्दजाल नहीं, सरल सुलभ भाषा", es: "Lenguaje llano y accesible antes que jerga", fr: "Une langue simple et accessible plutôt que du jargon", ar: "لغة بسيطة ميسّرة بدل المصطلحات المعقدة", pt: "Linguagem simples e acessível em vez de jargão", ru: "Простой, доступный язык вместо жаргона", de: "Klare, zugängliche Sprache statt Jargon", ja: "専門用語より、平易でわかりやすい言葉を" },
  comCheck3: { en: "Claims backed by primary sources you cite", nl: "Beweringen onderbouwd met primaire bronnen die je citeert", zh: "论断有你引用的一手来源支撑", hi: "दावे आपके उद्धृत प्राथमिक स्रोतों से समर्थित", es: "Afirmaciones respaldadas por fuentes primarias citadas", fr: "Des affirmations étayées par les sources primaires que vous citez", ar: "ادعاءات مدعومة بمصادر أولية تستشهد بها", pt: "Afirmações apoiadas por fontes primárias citadas", ru: "Утверждения, подкреплённые первоисточниками", de: "Aussagen belegt durch zitierte Primärquellen", ja: "主張は引用した一次資料で裏づける" },
  comCheck4: { en: "Related concepts linked so the graph stays connected", nl: "Verwante concepten gelinkt zodat de graaf verbonden blijft", zh: "关联概念相互链接，让图谱保持连通", hi: "संबंधित अवधारणाएँ जुड़ी हों ताकि ग्राफ़ जुड़ा रहे", es: "Conceptos relacionados enlazados para que el grafo siga conectado", fr: "Des concepts liés reliés entre eux pour que le graphe reste connecté", ar: "مفاهيم ذات صلة مترابطة ليبقى الرسم البياني متصلاً", pt: "Conceitos relacionados linkados para o grafo continuar conectado", ru: "Связанные понятия соединены, чтобы граф оставался цельным", de: "Verwandte Konzepte verlinkt, damit der Graph verbunden bleibt", ja: "関連する概念をリンクし、グラフのつながりを保つ" },
  comCheck5: { en: "Respect the ~68ch measure — write for calm reading", nl: "Respecteer de maat van ~68 tekens — schrijf voor rustig lezen", zh: "遵守约 68 字符的行宽——为从容阅读而写", hi: "~68 अक्षर की माप का सम्मान करें — शांत पठन के लिए लिखें", es: "Respeta la medida de ~68 caracteres: escribe para una lectura serena", fr: "Respectez la mesure d'environ 68 caractères — écrivez pour une lecture apaisée", ar: "احترم عرض السطر (~68 حرفاً) — اكتب لقراءة هادئة", pt: "Respeite a medida de ~68 caracteres — escreva para uma leitura calma", ru: "Соблюдайте меру ~68 знаков — пишите для спокойного чтения", de: "Halte das Maß von ~68 Zeichen ein — schreibe für ruhiges Lesen", ja: "約68字の行長を守り、落ち着いて読める文章を" },
  comCheck6: { en: "Shared freely under CC BY-SA 4.0", nl: "Vrij gedeeld onder CC BY-SA 4.0", zh: "以 CC BY-SA 4.0 自由共享", hi: "CC BY-SA 4.0 के अंतर्गत मुक्त रूप से साझा", es: "Compartido libremente bajo CC BY-SA 4.0", fr: "Partagé librement sous CC BY-SA 4.0", ar: "يُشارك بحرية بموجب CC BY-SA 4.0", pt: "Compartilhado livremente sob CC BY-SA 4.0", ru: "Свободно распространяется по CC BY-SA 4.0", de: "Frei geteilt unter CC BY-SA 4.0", ja: "CC BY-SA 4.0 のもとで自由に共有" },
  comRoles: { en: "Roles in the ecosystem", nl: "Rollen in het ecosysteem", zh: "生态系统中的角色", hi: "पारितंत्र में भूमिकाएँ", es: "Roles en el ecosistema", fr: "Rôles dans l'écosystème", ar: "الأدوار في المنظومة", pt: "Papéis no ecossistema", ru: "Роли в экосистеме", de: "Rollen im Ökosystem", ja: "エコシステムの役割" },
  comRole1: { en: "Reader", nl: "Lezer", zh: "读者", hi: "पाठक", es: "Lector", fr: "Lecteur", ar: "قارئ", pt: "Leitor", ru: "Читатель", de: "Leser:in", ja: "読者" },
  comRole1b: { en: "Explore freely, save collections, take private notes.", nl: "Verken vrij, bewaar collecties, maak privénotities.", zh: "自由探索、保存收藏、做私人笔记。", hi: "स्वतंत्र रूप से खोजें, संग्रह सहेजें, निजी नोट्स लें।", es: "Explora libremente, guarda colecciones, toma notas privadas.", fr: "Explorez librement, enregistrez des collections, prenez des notes privées.", ar: "استكشف بحرية واحفظ المجموعات ودوّن ملاحظات خاصة.", pt: "Explore livremente, salve coleções, faça notas privadas.", ru: "Свободно исследуйте, сохраняйте подборки, ведите личные заметки.", de: "Frei erkunden, Sammlungen speichern, private Notizen machen.", ja: "自由に探索し、コレクションを保存し、非公開メモを取る。" },
  comRole2: { en: "Contributor", nl: "Bijdrager", zh: "贡献者", hi: "योगदानकर्ता", es: "Colaborador", fr: "Contributeur", ar: "مساهم", pt: "Colaborador", ru: "Участник", de: "Mitwirkende:r", ja: "コントリビューター" },
  comRole2b: { en: "Edit and write articles, suggest connections, open discussions.", nl: "Bewerk en schrijf artikelen, stel verbindingen voor, open discussies.", zh: "编辑与撰写文章、建议连接、发起讨论。", hi: "लेख लिखें और संपादित करें, संबंध सुझाएँ, चर्चाएँ खोलें।", es: "Edita y escribe artículos, sugiere conexiones, abre discusiones.", fr: "Modifiez et écrivez des articles, suggérez des connexions, ouvrez des discussions.", ar: "حرر واكتب المقالات واقترح الروابط وافتح النقاشات.", pt: "Edite e escreva artigos, sugira conexões, abra discussões.", ru: "Пишите и правьте статьи, предлагайте связи, открывайте обсуждения.", de: "Artikel bearbeiten und schreiben, Verbindungen vorschlagen, Diskussionen eröffnen.", ja: "記事を編集・執筆し、つながりを提案し、議論を開く。" },
  comRole3: { en: "Reviewer", nl: "Reviewer", zh: "评审者", hi: "समीक्षक", es: "Revisor", fr: "Relecteur", ar: "مراجع", pt: "Revisor", ru: "Рецензент", de: "Reviewer:in", ja: "レビュアー" },
  comRole3b: { en: "Review pull requests and shepherd contributions toward merge.", nl: "Review pull requests en begeleid bijdragen richting merge.", zh: "评审拉取请求，引导贡献走向合并。", hi: "पुल रिक्वेस्ट की समीक्षा करें और योगदान को मर्ज तक ले जाएँ।", es: "Revisa pull requests y acompaña las contribuciones hasta el merge.", fr: "Relisez les pull requests et guidez les contributions jusqu'au merge.", ar: "راجع طلبات السحب وارعَ المساهمات حتى الدمج.", pt: "Revise pull requests e conduza contribuições até o merge.", ru: "Рецензируйте pull request'ы и ведите вклады к слиянию.", de: "Pull Requests prüfen und Beiträge zum Merge begleiten.", ja: "プルリクエストをレビューし、貢献をマージへ導く。" },
  comRole4: { en: "Expert", nl: "Expert", zh: "专家", hi: "विशेषज्ञ", es: "Experto", fr: "Expert", ar: "خبير", pt: "Especialista", ru: "Эксперт", de: "Expert:in", ja: "専門家" },
  comRole4b: { en: "Verify facts in your domain and sign off on accuracy.", nl: "Verifieer feiten in je domein en teken voor juistheid.", zh: "核实你所在领域的事实并确认其准确性。", hi: "अपने क्षेत्र के तथ्य सत्यापित करें और सटीकता की पुष्टि करें।", es: "Verifica los hechos de tu dominio y avala su exactitud.", fr: "Vérifiez les faits de votre domaine et attestez de leur exactitude.", ar: "تحقق من حقائق مجالك وصادق على دقتها.", pt: "Verifique os fatos do seu domínio e ateste a exatidão.", ru: "Проверяйте факты в своей области и подтверждайте точность.", de: "Fakten im eigenen Fachgebiet prüfen und Richtigkeit bestätigen.", ja: "自分の分野の事実を検証し、正確さを承認する。" },
  comRole5: { en: "Maintainer", nl: "Beheerder", zh: "维护者", hi: "अनुरक्षक", es: "Mantenedor", fr: "Mainteneur", ar: "مشرف", pt: "Mantenedor", ru: "Мейнтейнер", de: "Maintainer:in", ja: "メンテナー" },
  comRole5b: { en: "Steward a domain, resolve disputes and shape the roadmap.", nl: "Beheer een domein, los geschillen op en vorm de roadmap.", zh: "守护一个领域、化解分歧并塑造路线图。", hi: "किसी क्षेत्र की देखरेख करें, विवाद सुलझाएँ और रोडमैप गढ़ें।", es: "Custodia un dominio, resuelve disputas y da forma a la hoja de ruta.", fr: "Prenez soin d'un domaine, résolvez les différends et façonnez la feuille de route.", ar: "ارعَ مجالاً وحل الخلافات وارسم خارطة الطريق.", pt: "Cuide de um domínio, resolva disputas e molde o roadmap.", ru: "Опекайте область, разрешайте споры и формируйте дорожную карту.", de: "Einen Bereich betreuen, Streitfälle klären und die Roadmap gestalten.", ja: "分野を管理し、対立を解決し、ロードマップを形づくる。" },
  comEveryPage: { en: "Every page carries", nl: "Elke pagina draagt", zh: "每一页都带有", hi: "हर पृष्ठ में है", es: "Cada página lleva", fr: "Chaque page porte", ar: "تحمل كل صفحة", pt: "Cada página carrega", ru: "На каждой странице", de: "Jede Seite trägt", ja: "すべてのページに備わるもの" },

  // Not found / offline
  nfLabel: { en: "Off the map", nl: "Buiten de kaart", zh: "地图之外", hi: "नक्शे से बाहर", es: "Fuera del mapa", fr: "Hors de la carte", ar: "خارج الخريطة", pt: "Fora do mapa", ru: "За краем карты", de: "Abseits der Karte", ja: "地図の外へ" },
  nfBody: { en: "This path hasn't grown here — yet. Even in nature, some trails lead nowhere. Let's get you back to the living graph.", nl: "Dit pad is hier nog niet gegroeid. Ook in de natuur lopen sommige sporen dood. We brengen je terug naar de levende graaf.", zh: "这条路径尚未在此生长。即使在自然中，有些小径也通向虚无。让我们带你回到活的图谱。", hi: "यह पथ यहाँ अभी नहीं उगा है। प्रकृति में भी कुछ पगडंडियाँ कहीं नहीं ले जातीं। चलिए आपको जीवंत ग्राफ़ पर वापस ले चलें।", es: "Este camino aún no ha crecido aquí. Incluso en la naturaleza, algunos senderos no llevan a ninguna parte. Volvamos al grafo vivo.", fr: "Ce chemin n'a pas encore poussé ici. Même dans la nature, certains sentiers ne mènent nulle part. Revenons au graphe vivant.", ar: "لم ينبت هذا الطريق هنا بعد. حتى في الطبيعة، بعض الدروب لا تؤدي إلى شيء. لنعدك إلى الرسم البياني الحي.", pt: "Este caminho ainda não cresceu aqui. Mesmo na natureza, algumas trilhas não levam a lugar algum. Vamos levá-lo de volta ao grafo vivo.", ru: "Эта тропа здесь ещё не выросла. Даже в природе некоторые тропинки никуда не ведут. Вернём вас к живому графу.", de: "Dieser Pfad ist hier noch nicht gewachsen. Selbst in der Natur führen manche Spuren ins Nichts. Zurück zum lebendigen Graphen.", ja: "この道はまだここに育っていません。自然の中でも、行き止まりの小道はあります。生きたグラフへ戻りましょう。" },
  nfHome: { en: "Return home", nl: "Terug naar home", zh: "返回首页", hi: "होम पर लौटें", es: "Volver al inicio", fr: "Retour à l'accueil", ar: "العودة إلى الرئيسية", pt: "Voltar ao início", ru: "На главную", de: "Zur Startseite", ja: "ホームへ戻る" },
  nfOffline: { en: "No connection", nl: "Geen verbinding", zh: "无网络连接", hi: "कोई कनेक्शन नहीं", es: "Sin conexión", fr: "Pas de connexion", ar: "لا يوجد اتصال", pt: "Sem conexão", ru: "Нет соединения", de: "Keine Verbindung", ja: "接続がありません" },
  nfOfflineHead: { en: "The ecosystem is resting.", nl: "Het ecosysteem rust even.", zh: "生态系统正在休憩。", hi: "पारितंत्र विश्राम कर रहा है।", es: "El ecosistema está descansando.", fr: "L'écosystème se repose.", ar: "المنظومة تستريح.", pt: "O ecossistema está descansando.", ru: "Экосистема отдыхает.", de: "Das Ökosystem ruht sich aus.", ja: "生態系は休んでいます。" },
  nfOfflineBody: { en: "You're offline. Pages you've already visited remain available; the rest will return the moment you reconnect.", nl: "Je bent offline. Pagina's die je al hebt bezocht blijven beschikbaar; de rest keert terug zodra je weer verbinding hebt.", zh: "你已离线。访问过的页面仍然可用；其余的会在你重新联网时立刻回来。", hi: "आप ऑफ़लाइन हैं। जो पृष्ठ आपने देखे हैं वे उपलब्ध रहेंगे; बाकी पुनः कनेक्ट होते ही लौट आएँगे।", es: "Estás sin conexión. Las páginas que ya visitaste siguen disponibles; el resto volverá en cuanto te reconectes.", fr: "Vous êtes hors ligne. Les pages déjà visitées restent disponibles ; le reste reviendra dès votre reconnexion.", ar: "أنت غير متصل. تبقى الصفحات التي زرتها متاحة؛ ويعود الباقي فور إعادة الاتصال.", pt: "Você está offline. As páginas já visitadas continuam disponíveis; o resto volta assim que você se reconectar.", ru: "Вы офлайн. Уже посещённые страницы доступны; остальные вернутся, как только появится соединение.", de: "Du bist offline. Bereits besuchte Seiten bleiben verfügbar; der Rest kehrt zurück, sobald du wieder verbunden bist.", ja: "オフラインです。訪れたページは引き続き利用できます。残りは再接続した瞬間に戻ってきます。" },
  nfTryHome: { en: "Try home", nl: "Probeer home", zh: "回到首页", hi: "होम आज़माएँ", es: "Probar el inicio", fr: "Essayer l'accueil", ar: "جرّب الرئيسية", pt: "Tentar o início", ru: "Попробовать главную", de: "Startseite versuchen", ja: "ホームを試す" },

  // About page
  abLabel: { en: "The mission", nl: "De missie", zh: "使命", hi: "मिशन", es: "La misión", fr: "La mission", ar: "المهمة", pt: "A missão", ru: "Миссия", de: "Die Mission", ja: "ミッション" },
  abHeadline: { en: "Make humanity's ecological knowledge freely accessible, beautifully organized and endlessly connected.", nl: "Maak de ecologische kennis van de mensheid vrij toegankelijk, prachtig geordend en eindeloos verbonden.", zh: "让人类的生态知识自由开放、井然有序、无尽相连。", hi: "मानवता के पारिस्थितिक ज्ञान को स्वतंत्र रूप से सुलभ, सुंदर ढंग से व्यवस्थित और अनंत रूप से जुड़ा बनाना।", es: "Hacer el conocimiento ecológico de la humanidad libremente accesible, bellamente organizado e infinitamente conectado.", fr: "Rendre le savoir écologique de l'humanité librement accessible, magnifiquement organisé et infiniment relié.", ar: "جعل معرفة البشرية البيئية متاحة بحرية ومنظمة بجمال ومترابطة بلا حدود.", pt: "Tornar o conhecimento ecológico da humanidade livremente acessível, lindamente organizado e infinitamente conectado.", ru: "Сделать экологические знания человечества свободно доступными, изящно упорядоченными и бесконечно связанными.", de: "Das ökologische Wissen der Menschheit frei zugänglich, wunderbar geordnet und endlos vernetzt machen.", ja: "人類の生態学的知識を、自由に開かれ、美しく整理され、限りなくつながったものに。" },
  abP1: { en: "Equilibrium is a living ecosystem of knowledge — not a blog, not documentation. It is the Wikipedia, GitHub, Notion and Obsidian of ecology, regenerative design, permaculture, biology, soil science, food forests, climate adaptation and systems thinking, gathered into a single connected whole.", nl: "Equilibrium is een levend kennisecosysteem — geen blog, geen documentatie. Het is de Wikipedia, GitHub, Notion en Obsidian van ecologie, regeneratief ontwerp, permacultuur, biologie, bodemkunde, voedselbossen, klimaatadaptatie en systeemdenken, samengebracht in één verbonden geheel.", zh: "Equilibrium 是一个活的知识生态系统——不是博客，也不是文档。它是生态学、再生设计、朴门永续、生物学、土壤科学、食物森林、气候适应与系统思维领域的 Wikipedia、GitHub、Notion 与 Obsidian，汇聚成一个相连的整体。", hi: "Equilibrium ज्ञान का जीवंत पारितंत्र है — न ब्लॉग, न दस्तावेज़ीकरण। यह पारिस्थितिकी, पुनर्योजी डिज़ाइन, पर्माकल्चर, जीवविज्ञान, मृदा विज्ञान, खाद्य वन, जलवायु अनुकूलन और सिस्टम चिंतन का Wikipedia, GitHub, Notion और Obsidian है — एक जुड़े हुए समग्र में समेटा हुआ।", es: "Equilibrium es un ecosistema vivo de conocimiento: ni un blog ni documentación. Es la Wikipedia, GitHub, Notion y Obsidian de la ecología, el diseño regenerativo, la permacultura, la biología, la ciencia del suelo, los bosques comestibles, la adaptación climática y el pensamiento sistémico, reunidos en un todo conectado.", fr: "Equilibrium est un écosystème vivant de savoir — ni un blog, ni de la documentation. C'est le Wikipédia, le GitHub, le Notion et l'Obsidian de l'écologie, du design régénératif, de la permaculture, de la biologie, de la science des sols, des forêts nourricières, de l'adaptation climatique et de la pensée systémique, rassemblés en un tout relié.", ar: "Equilibrium منظومة معرفة حية — ليس مدونة ولا توثيقاً. إنه Wikipedia وGitHub وNotion وObsidian لعلوم البيئة والتصميم التجديدي والزراعة المستدامة والأحياء وعلوم التربة وغابات الغذاء والتكيف المناخي والتفكير المنظومي، مجموعة في كلٍّ واحد مترابط.", pt: "O Equilibrium é um ecossistema vivo de conhecimento — não um blog, não documentação. É a Wikipedia, o GitHub, o Notion e o Obsidian da ecologia, design regenerativo, permacultura, biologia, ciência do solo, florestas alimentares, adaptação climática e pensamento sistêmico, reunidos em um todo conectado.", ru: "Equilibrium — живая экосистема знаний, не блог и не документация. Это Wikipedia, GitHub, Notion и Obsidian экологии, регенеративного дизайна, пермакультуры, биологии, почвоведения, пищевых лесов, климатической адаптации и системного мышления, собранные в единое связанное целое.", de: "Equilibrium ist ein lebendiges Wissensökosystem — kein Blog, keine Dokumentation. Es ist das Wikipedia, GitHub, Notion und Obsidian von Ökologie, regenerativem Design, Permakultur, Biologie, Bodenkunde, Waldgärten, Klimaanpassung und Systemdenken, versammelt in einem verbundenen Ganzen.", ja: "Equilibrium は生きた知識の生態系です——ブログでもドキュメントでもありません。生態学、リジェネラティブデザイン、パーマカルチャー、生物学、土壌科学、フードフォレスト、気候適応、システム思考の Wikipedia・GitHub・Notion・Obsidian を、ひとつのつながった全体にまとめたものです。" },
  abP2: { en: "We believe knowledge should behave like nature: interconnected, evolving, adaptive, discoverable, beautiful and open. Every page should feel like discovering a hidden ecosystem — and every discovery should lead to the next.", nl: "Wij geloven dat kennis zich als natuur moet gedragen: verbonden, evoluerend, adaptief, vindbaar, mooi en open. Elke pagina moet voelen als het ontdekken van een verborgen ecosysteem — en elke ontdekking moet naar de volgende leiden.", zh: "我们相信知识应像自然一样：互联、演化、自适应、可发现、美丽且开放。每一页都应像发现一个隐秘的生态系统——每一次发现都应引向下一次。", hi: "हम मानते हैं कि ज्ञान को प्रकृति की तरह होना चाहिए: परस्पर जुड़ा, विकसित होता, अनुकूल, खोजने योग्य, सुंदर और खुला। हर पृष्ठ किसी छिपे पारितंत्र की खोज जैसा लगे — और हर खोज अगली की ओर ले जाए।", es: "Creemos que el conocimiento debería comportarse como la naturaleza: interconectado, evolutivo, adaptable, descubrible, bello y abierto. Cada página debería sentirse como descubrir un ecosistema oculto, y cada descubrimiento debería llevar al siguiente.", fr: "Nous croyons que le savoir devrait se comporter comme la nature : interconnecté, évolutif, adaptatif, découvrable, beau et ouvert. Chaque page devrait donner l'impression de découvrir un écosystème caché — et chaque découverte devrait mener à la suivante.", ar: "نؤمن بأن المعرفة يجب أن تسلك سلوك الطبيعة: مترابطة، متطورة، متكيفة، قابلة للاكتشاف، جميلة ومفتوحة. كل صفحة ينبغي أن تشبه اكتشاف منظومة خفية — وكل اكتشاف يقود إلى التالي.", pt: "Acreditamos que o conhecimento deve se comportar como a natureza: interligado, evolutivo, adaptável, descobrível, belo e aberto. Cada página deve parecer a descoberta de um ecossistema oculto — e cada descoberta deve levar à próxima.", ru: "Мы верим, что знание должно вести себя как природа: взаимосвязанно, эволюционно, адаптивно, открыто и красиво. Каждая страница — как открытие скрытой экосистемы, и каждое открытие ведёт к следующему.", de: "Wir glauben, Wissen sollte sich wie Natur verhalten: vernetzt, evolvierend, anpassungsfähig, entdeckbar, schön und offen. Jede Seite sollte sich anfühlen wie die Entdeckung eines verborgenen Ökosystems — und jede Entdeckung zur nächsten führen.", ja: "知識は自然のようにあるべきだと私たちは信じています。相互につながり、進化し、適応し、発見でき、美しく、開かれている。すべてのページが隠れた生態系の発見のように感じられ、その発見が次の発見へつながるべきです。" },
  abSideBrand: { en: "A side brand of GRØNN Studio", nl: "Een zustermerk van GRØNN Studio", zh: "GRØNN Studio 的副品牌", hi: "GRØNN Studio का सह-ब्रांड", es: "Una marca hermana de GRØNN Studio", fr: "Une marque sœur de GRØNN Studio", ar: "علامة فرعية من GRØNN Studio", pt: "Uma marca paralela do GRØNN Studio", ru: "Дочерний бренд GRØNN Studio", de: "Eine Nebenmarke von GRØNN Studio", ja: "GRØNN Studio のサイドブランド" },
  abP3pre: { en: "Equilibrium is stewarded by", nl: "Equilibrium wordt beheerd door", zh: "Equilibrium 由", hi: "Equilibrium का संरक्षण", es: "Equilibrium está al cuidado de", fr: "Equilibrium est entretenu par", ar: "يرعى Equilibrium", pt: "O Equilibrium é cuidado pelo", ru: "Equilibrium опекает", de: "Equilibrium wird betreut von", ja: "Equilibrium を支えるのは" },
  abP3post: { en: ", an ecological design practice. Where the studio designs living landscapes in the world, Equilibrium tends the knowledge that makes that work possible — and gives it away.", nl: ", een ecologisch ontwerpbureau. Waar de studio levende landschappen in de wereld ontwerpt, verzorgt Equilibrium de kennis die dat werk mogelijk maakt — en geeft die weg.", zh: "（一家生态设计工作室）守护。工作室在世界中设计有生命的景观，而 Equilibrium 则照料让这项工作成为可能的知识——并将其无偿分享。", hi: "करता है, जो एक पारिस्थितिक डिज़ाइन संस्था है। जहाँ स्टूडियो दुनिया में जीवंत परिदृश्य रचता है, वहीं Equilibrium उस ज्ञान को सँवारता है जो वह काम संभव बनाता है — और उसे मुफ़्त बाँटता है।", es: ", un estudio de diseño ecológico. Mientras el estudio diseña paisajes vivos en el mundo, Equilibrium cuida el conocimiento que hace posible ese trabajo, y lo regala.", fr: ", une pratique de design écologique. Là où le studio conçoit des paysages vivants dans le monde, Equilibrium cultive le savoir qui rend ce travail possible — et l'offre.", ar: "، وهو ممارسة تصميم بيئي. بينما يصمم الاستوديو مناظر طبيعية حية في العالم، يرعى Equilibrium المعرفة التي تجعل ذلك العمل ممكناً — ويمنحها مجاناً.", pt: ", uma prática de design ecológico. Enquanto o estúdio projeta paisagens vivas no mundo, o Equilibrium cuida do conhecimento que torna esse trabalho possível — e o distribui gratuitamente.", ru: " — студия экологического дизайна. Пока студия проектирует живые ландшафты в мире, Equilibrium взращивает знания, делающие эту работу возможной, — и отдаёт их даром.", de: ", einer Praxis für ökologisches Design. Während das Studio lebendige Landschaften in der Welt gestaltet, pflegt Equilibrium das Wissen, das diese Arbeit möglich macht — und verschenkt es.", ja: "、生態デザインの実践者です。スタジオが世界に生きた景観をデザインする一方で、Equilibrium はその仕事を可能にする知識を育て——そして無償で分かち合います。" },
  abPrinciples: { en: "Principles", nl: "Principes", zh: "原则", hi: "सिद्धांत", es: "Principios", fr: "Principes", ar: "المبادئ", pt: "Princípios", ru: "Принципы", de: "Prinzipien", ja: "原則" },
  abPrin1: { en: "Everything is connected — no page is an island.", nl: "Alles is verbonden — geen pagina is een eiland.", zh: "万物相连——没有一页是孤岛。", hi: "सब कुछ जुड़ा है — कोई पृष्ठ द्वीप नहीं।", es: "Todo está conectado: ninguna página es una isla.", fr: "Tout est relié — aucune page n'est une île.", ar: "كل شيء مترابط — لا صفحة جزيرة معزولة.", pt: "Tudo está conectado — nenhuma página é uma ilha.", ru: "Всё связано — ни одна страница не остров.", de: "Alles ist verbunden — keine Seite ist eine Insel.", ja: "すべてはつながっている——孤島のページはない。" },
  abPrin2: { en: "Knowledge should behave like nature: interconnected, evolving, adaptive, open.", nl: "Kennis moet zich gedragen als natuur: verbonden, evoluerend, adaptief, open.", zh: "知识应像自然：互联、演化、自适应、开放。", hi: "ज्ञान प्रकृति जैसा हो: परस्पर जुड़ा, विकसित होता, अनुकूल, खुला।", es: "El conocimiento debería comportarse como la naturaleza: interconectado, evolutivo, adaptable, abierto.", fr: "Le savoir devrait se comporter comme la nature : interconnecté, évolutif, adaptatif, ouvert.", ar: "ينبغي للمعرفة أن تسلك سلوك الطبيعة: مترابطة، متطورة، متكيفة، مفتوحة.", pt: "O conhecimento deve se comportar como a natureza: interligado, evolutivo, adaptável, aberto.", ru: "Знание должно вести себя как природа: взаимосвязанно, эволюционно, адаптивно, открыто.", de: "Wissen sollte sich wie Natur verhalten: vernetzt, evolvierend, anpassungsfähig, offen.", ja: "知識は自然のようにあるべき：相互につながり、進化し、適応し、開かれている。" },
  abPrin3: { en: "Whitespace is a feature; clarity is a form of respect.", nl: "Witruimte is een feature; helderheid is een vorm van respect.", zh: "留白是一种功能；清晰是一种尊重。", hi: "रिक्त स्थान एक विशेषता है; स्पष्टता सम्मान का रूप है।", es: "El espacio en blanco es una virtud; la claridad es una forma de respeto.", fr: "L'espace blanc est une qualité ; la clarté est une forme de respect.", ar: "المساحات البيضاء ميزة؛ والوضوح شكل من الاحترام.", pt: "O espaço em branco é um recurso; a clareza é uma forma de respeito.", ru: "Пустое пространство — достоинство; ясность — форма уважения.", de: "Weißraum ist ein Feature; Klarheit ist eine Form von Respekt.", ja: "余白は機能であり、明晰さは敬意のかたちである。" },
  abPrin4: { en: "Every animation has a purpose, or it does not exist.", nl: "Elke animatie heeft een doel, of ze bestaat niet.", zh: "每个动画都有目的，否则它就不该存在。", hi: "हर एनीमेशन का एक उद्देश्य है, वरना उसका अस्तित्व नहीं।", es: "Cada animación tiene un propósito, o no existe.", fr: "Chaque animation a un but, ou elle n'existe pas.", ar: "لكل حركة غرض، وإلا فلا وجود لها.", pt: "Toda animação tem um propósito, ou não existe.", ru: "У каждой анимации есть цель — иначе её нет.", de: "Jede Animation hat einen Zweck, oder sie existiert nicht.", ja: "すべてのアニメーションには目的がある。なければ存在しない。" },
  abPrin5: { en: "Free to read, free to fork, free forever.", nl: "Vrij te lezen, vrij te forken, voor altijd vrij.", zh: "自由阅读，自由复刻，永远免费。", hi: "पढ़ने को मुक्त, फ़ोर्क करने को मुक्त, सदा के लिए मुक्त।", es: "Libre para leer, libre para bifurcar, libre para siempre.", fr: "Libre à lire, libre à forker, libre pour toujours.", ar: "حر للقراءة، حر للنسخ، حر إلى الأبد.", pt: "Livre para ler, livre para fazer fork, livre para sempre.", ru: "Свободно читать, свободно форкать, свободно навсегда.", de: "Frei zu lesen, frei zu forken, für immer frei.", ja: "自由に読め、自由にフォークでき、永遠に自由。" },
  abLicence: { en: "Licence", nl: "Licentie", zh: "许可协议", hi: "लाइसेंस", es: "Licencia", fr: "Licence", ar: "الرخصة", pt: "Licença", ru: "Лицензия", de: "Lizenz", ja: "ライセンス" },
  abLicPre: { en: "All content is published under", nl: "Alle inhoud wordt gepubliceerd onder", zh: "所有内容均以", hi: "सारी सामग्री", es: "Todo el contenido se publica bajo", fr: "Tout le contenu est publié sous", ar: "يُنشر كل المحتوى بموجب", pt: "Todo o conteúdo é publicado sob", ru: "Весь контент публикуется под лицензией", de: "Alle Inhalte erscheinen unter", ja: "すべてのコンテンツは" },
  abLicMid: { en: ": free to share and adapt, with attribution, forever. The platform itself is open source on", nl: ": vrij te delen en te bewerken, met naamsvermelding, voor altijd. Het platform zelf is open source op", zh: "发布：可自由分享与改编，需署名，永久有效。平台本身开源于", hi: "के अंतर्गत प्रकाशित है: साझा करने और ढालने को मुक्त, श्रेय सहित, सदा के लिए। प्लेटफ़ॉर्म स्वयं ओपन सोर्स है", es: ": libre para compartir y adaptar, con atribución, para siempre. La plataforma en sí es de código abierto en", fr: " : libre de partage et d'adaptation, avec attribution, pour toujours. La plateforme elle-même est open source sur", ar: ": حر للمشاركة والتعديل، مع الإسناد، إلى الأبد. المنصة نفسها مفتوحة المصدر على", pt: ": livre para compartilhar e adaptar, com atribuição, para sempre. A própria plataforma é open source no", ru: ": свободно делиться и адаптировать, с указанием авторства, навсегда. Сама платформа — открытый код на", de: ": frei zu teilen und zu bearbeiten, mit Namensnennung, für immer. Die Plattform selbst ist Open Source auf", ja: "の下で公開：帰属表示のうえで、共有も翻案も自由、永遠に。プラットフォーム自体もオープンソースです——" },
  abLicPost: { en: ".", nl: ".", zh: "。", hi: "।", es: ".", fr: ".", ar: ".", pt: ".", ru: ".", de: ".", ja: "。" },
  abPaths: { en: "Paths", nl: "Routes", zh: "路径", hi: "पथ", es: "Rutas", fr: "Parcours", ar: "مسارات", pt: "Trilhas", ru: "Маршруты", de: "Pfade", ja: "パス" },
  abEnter: { en: "Enter the ecosystem", nl: "Betreed het ecosysteem", zh: "进入生态系统", hi: "पारितंत्र में प्रवेश करें", es: "Entra al ecosistema", fr: "Entrer dans l'écosystème", ar: "ادخل المنظومة", pt: "Entre no ecossistema", ru: "Войти в экосистему", de: "Das Ökosystem betreten", ja: "生態系に入る" },
} satisfies Record<string, L>
